class IdentityRunner{
	public static void main(String []rud){
	String name1="Rudra";
	String name2="Prashant";
	String name3="Veeresh";
	String name4="Akhilesh";
	String name5="Malku";
	String name6="Nagu";
	String name7="Bassu";
	String name8="Praveen";
	String name9="Rohith";
	String name10="VijaySai";
	String name11="Abhishek";
	String name12="Srikanth Reddy";
	Identity.printName(name1);
	Identity.printName(name2);
	Identity.printName(name3);
	Identity.printName(name4);
	Identity.printName(name5);
	Identity.printName(name6);
	Identity.printName(name7);
	Identity.printName(name8);
	Identity.printName(name9);
	Identity.printName(name10);
	Identity.printName(name11);
	Identity.printName(name12);
	String email1="rudreshwar@gmail.com";
	String email2="Akhilesh@gmail.com";
	String email3="Veeresh@gmail.com";
	String email4="Prashant@gmail.com";
	String email5="Malku@gmail.com";
	String email6="Nagu@gmail.com";
	String email7="Bassu@gmail.com";
	String email8="Praveen@gmail.com";
	String email9="Rohith@gmail.com";
	String email10="VijaySai@gmail.com";
	String email11="Abhishek@gmail.com";
	String email12="Srikanth@gmail.com";
	Identity.printNameAndEmail(name1,email1);
	Identity.printNameAndEmail(name2,email2);
	Identity.printNameAndEmail(name3,email3);
	Identity.printNameAndEmail(name4,email4);
	Identity.printNameAndEmail(name5,email5);
	Identity.printNameAndEmail(name6,email6);
	Identity.printNameAndEmail(name7,email7);
	Identity.printNameAndEmail(name8,email8);
	Identity.printNameAndEmail(name9,email9);
	Identity.printNameAndEmail(name10,email10);
	Identity.printNameAndEmail(name11,email11);
	Identity.printNameAndEmail(name12,email12);
	double mobile1=8088928928d;
	double mobile2=7676928928d;
	double mobile3=9448928928d;
	double mobile4=9590928928d;
	double mobile5=8904165928d;
	double mobile6=8904164928d;
	double mobile7=9482540194d;
	double mobile8=6364689303d;
	double mobile9=9945999999d;
	double mobile10=8888666644d;
	double mobile11=9999999999d;
	double mobile12=9620780509d;
	Identity.printNameAndMobile(name1,mobile1);
	Identity.printNameAndMobile(name2,mobile2);
	Identity.printNameAndMobile(name3,mobile3);
	Identity.printNameAndMobile(name4,mobile4);
	Identity.printNameAndMobile(name5,mobile5);
	Identity.printNameAndMobile(name6,mobile6);
	Identity.printNameAndMobile(name7,mobile7);
	Identity.printNameAndMobile(name8,mobile8);
	Identity.printNameAndMobile(name9,mobile9);
	Identity.printNameAndMobile(name10,mobile10);
	Identity.printNameAndMobile(name12,mobile11);
	Identity.printNameAndMobile(name12,mobile12);
	int Age1=22;
	int Age2=23;
	int Age3=24;
	int Age4=25;
	int Age5=22;
	int Age6=24;
	int Age7=23;
	int Age8=21;
	int Age9=20;
	int Age10=21;
	int Age11=22;
	int Age12=23;
	Identity.printNameAndAge(name1,Age1);
	Identity.printNameAndAge(name2,Age2);
	Identity.printNameAndAge(name3,Age3);
	Identity.printNameAndAge(name4,Age4);
	Identity.printNameAndAge(name5,Age5);
	Identity.printNameAndAge(name6,Age6);
	Identity.printNameAndAge(name7,Age7);
	Identity.printNameAndAge(name8,Age8);
	Identity.printNameAndAge(name9,Age9);
	Identity.printNameAndAge(name10,Age10);
	Identity.printNameAndAge(name11,Age11);
	Identity.printNameAndAge(name12,Age12);
	String Address1="Tadola";
	String Address2="Shapur";
	String Address3="Humnabad";
	String Address4="Kalburgi";
	String Address5="Kamalapur";
	String Address6="Basavakalyan";
	String Address7="Bhalki";
	String Address8="Bidar";
	String Address9="Aurad";
	String Address10="Belagavi";
	String Address11="Gadag";
	String Address12="Hpete";
	Identity.printNameAndAddress(name1,Address1);
	Identity.printNameAndAddress(name2,Address2);
	Identity.printNameAndAddress(name3,Address3);
	Identity.printNameAndAddress(name4,Address4);
	Identity.printNameAndAddress(name5,Address5);
	Identity.printNameAndAddress(name6,Address6);
	Identity.printNameAndAddress(name7,Address7);
	Identity.printNameAndAddress(name8,Address8);
	Identity.printNameAndAddress(name9,Address9);
	Identity.printNameAndAddress(name10,Address10);
	Identity.printNameAndAddress(name11,Address11);
	Identity.printNameAndAddress(name12,Address12);
	Identity.printNameAndEmailAndAddressAndAge(name1,email1,Address1,Age1);
	Identity.printNameAndEmailAndAddressAndAge(name2,email2,Address2,Age2);
	Identity.printNameAndEmailAndAddressAndAge(name3,email3,Address3,Age3);
	Identity.printNameAndEmailAndAddressAndAge(name4,email4,Address4,Age4);
	Identity.printNameAndEmailAndAddressAndAge(name5,email5,Address5,Age5);
	Identity.printNameAndEmailAndAddressAndAge(name6,email6,Address6,Age6);
	Identity.printNameAndEmailAndAddressAndAge(name7,email7,Address7,Age7);
	Identity.printNameAndEmailAndAddressAndAge(name8,email8,Address8,Age8);
	Identity.printNameAndEmailAndAddressAndAge(name9,email9,Address9,Age9);
	Identity.printNameAndEmailAndAddressAndAge(name10,email10,Address10,Age10);
	Identity.printNameAndEmailAndAddressAndAge(name11,email11,Address11,Age11);
	Identity.printNameAndEmailAndAddressAndAge(name12,email12,Address12,Age12);
	char Gender1='M';
	char Gender2='M';
	char Gender3='M';
	char Gender4='M';
	char Gender5='M';
	char Gender6='M';
	char Gender7='M';
	char Gender8='M';
	char Gender9='M';
	char Gender10='M';
	char Gender11='M';
	char Gender12='M';
	Identity.printNameAndGender(name1,Gender1);
	Identity.printNameAndGender(name2,Gender2);
	Identity.printNameAndGender(name3,Gender3);
	Identity.printNameAndGender(name4,Gender4);
	Identity.printNameAndGender(name5,Gender5);
	Identity.printNameAndGender(name6,Gender6);
	Identity.printNameAndGender(name7,Gender7);
	Identity.printNameAndGender(name8,Gender8);
	Identity.printNameAndGender(name9,Gender9);
	Identity.printNameAndGender(name10,Gender10);
	Identity.printNameAndGender(name11,Gender11);
	Identity.printNameAndGender(name12,Gender12);
	String Working1="Trainee";
	String Working2="Trainee";
	String Working3="Trainee";
	String Working4="Business";
	String Working5="Trainee";
	String Working6="No";
	String Working7="No";
	String Working8="Yes";
	String Working9="Yes";
	String Working10="Trainee";
	String Working11="No";
	String Working12="yes";
	Identity.printNameAndWorking(name1,Working1);
    Identity.printNameAndWorking(name2,Working2);
    Identity.printNameAndWorking(name3,Working3);
    Identity.printNameAndWorking(name4,Working4);
    Identity.printNameAndWorking(name5,Working5);
    Identity.printNameAndWorking(name6,Working6);
    Identity.printNameAndWorking(name7,Working7);
    Identity.printNameAndWorking(name8,Working8);
    Identity.printNameAndWorking(name9,Working9);
    Identity.printNameAndWorking(name10,Working10);
    Identity.printNameAndWorking(name11,Working11);
    Identity.printNameAndWorking(name12,Working12);
    char Size1='L'; 
    char Size2='M';	
	char Size3='X';
	char Size4='L';
	char Size5='M';
	char Size6='S';
	char Size7='X';
	char Size8='L';
	char Size9='L';
	char Size10='L';
	char Size11='L';
	char Size12='M';
	Identity.printNameAndShirtSize(name1,Size1);
    Identity.printNameAndShirtSize(name2,Size2);
    Identity.printNameAndShirtSize(name3,Size3);
    Identity.printNameAndShirtSize(name4,Size4);
    Identity.printNameAndShirtSize(name5,Size5);
    Identity.printNameAndShirtSize(name6,Size6);
    Identity.printNameAndShirtSize(name7,Size7);
    Identity.printNameAndShirtSize(name8,Size8);
    Identity.printNameAndShirtSize(name9,Size9);
    Identity.printNameAndShirtSize(name10,Size10);
    Identity.printNameAndShirtSize(name11,Size11);
    Identity.printNameAndShirtSize(name12,Size12);
	int size1=32;
	int size2=38;
	int size3=36;
	int size4=32;
    int size5=36;
	int size6=38;
	int size7=40;
	int size8=42;
	int size9=44;
	int size10=36;
	int size11=38;
	int size12=32;
	Identity.printNameAndPantsize(name1,size1);
	Identity.printNameAndPantsize(name2,size2);
	Identity.printNameAndPantsize(name3,size3);
	Identity.printNameAndPantsize(name4,size4);
	Identity.printNameAndPantsize(name5,size5);
	Identity.printNameAndPantsize(name6,size6);
	Identity.printNameAndPantsize(name7,size7);
	Identity.printNameAndPantsize(name8,size8);
	Identity.printNameAndPantsize(name9,size9);
	Identity.printNameAndPantsize(name10,size10);
	Identity.printNameAndPantsize(name11,size11);
	Identity.printNameAndPantsize(name12,size12);
	int weight1=63;
	int weight2=64;
	int weight3=68;
	int weight4=62;
	int weight5=60;
	int weight6=55;
	int weight7=66;
	int weight8=75;
	int weight9=70;
	int weight10=66;
	int weight11=65;
	int weight12=60;
	double height1=171.2;
	double height2=176.5;
	double height3=166;
	double height4=165.5;
	double height5=155.7;
	double height6=159.4;
	double height7=168;
	double height8=167.4;
	double height9=156.9;
	double height10=159.11;
	double height11=160.11;
	double height12=161;
	Identity.printNameAndWeightAndHeight(name1,weight1,height1);
	Identity.printNameAndWeightAndHeight(name2,weight2,height2);
	Identity.printNameAndWeightAndHeight(name3,weight3,height3);
	Identity.printNameAndWeightAndHeight(name4,weight4,height4);
	Identity.printNameAndWeightAndHeight(name5,weight5,height5);
	Identity.printNameAndWeightAndHeight(name6,weight6,height6);
	Identity.printNameAndWeightAndHeight(name7,weight7,height7);
	Identity.printNameAndWeightAndHeight(name8,weight8,height8);
	Identity.printNameAndWeightAndHeight(name9,weight9,height9);
	Identity.printNameAndWeightAndHeight(name10,weight10,height10);
	Identity.printNameAndWeightAndHeight(name11,weight11,height11);
	Identity.printNameAndWeightAndHeight(name12,weight12,height12);
	}
	
}